@Notifyer_HostAddress = https://localhost:7010

POST {{Notifyer_HostAddress}}/commands/subscribeToMachine
Content-Type: application/json

{
    "userId" : "some user id",
    "machineId" : "some machine id"
}

###


GET {{Notifyer_HostAddress}}/queries/Statistics

###
