@Notifyer_HostAddress = http://localhost:5216

POST {{Notifyer_HostAddress}}/commands/subscribeToMachine
Content-Type: application/json

{
    "userId" : "some user id",
    "machineId" : "some machine id"
}

###
